# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.cache/wt [current_project]
set_property parent.project_path C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/ctrlOut_endOut_expected.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/txDiagBus_QPSKConstellationPoints_re_expected.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/dataReady_expected.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/rxDiagBus_QPSKConstellationValid_expected.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/dataOut_re_expected.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/dataIn_re.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/rxDiagBus_QPSKConstellationPoints_im_expected.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/rxDiagBus_normCoarseFreqEst_expected.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/txDiagBus_QPSKConstellationPoints_im_expected.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/rxDiagBus_QPSKConstellationPoints_re_expected.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/txDiagBus_QPSKConstellationValid_expected.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/dataOut_im_expected.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/validIn.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/validOut_expected.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/dataIn.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/ctrlOut_startOut_expected.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/dataOut_expected.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/ctrlOut_validOut_expected.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/dataIn_im.dat
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/rxDiagBus_nSynced_expected.dat
}
read_vhdl -library xil_defaultlib {
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/QPSK_Rx_pkg.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/Compare_To_Constant5.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/RAM_Frame_Status_Indicator.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/SimpleDualPortRAM_singlebit.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/MATLAB_Function1.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/Data_Bits_FIFO.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/Compare_To_Constant2.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/Compare_To_Constant2_block.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/Preamble_Bits_Store.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/Preamble_Bits_Generator.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/Compare_To_Constant.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/Compare_To_Constant1.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/Bit_Packetizer.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/FilterCoef.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/FilterTapSystolicWvldin.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/subFilter.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/FilterCoef_block1.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/FilterCoef_block.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/Filter.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/HDL_Data_Scrambler.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/QPSK_Tx_pkg.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/QPSK_Modulator_Baseband.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/QPSK_Modulator.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/RRC_Filter.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/RRC_Transmit_Filter.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/QPSK_Tx.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/QPSK_Tx_tb_pkg.vhd
  C:/Users/lamy1/Documents/ECE460/QPSK_TxRx/QPSK_TxRx.srcs/sources_1/imports/commhdlQPSKTxRx/QPSK_Tx_tb.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top QPSK_Tx_tb -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef QPSK_Tx_tb.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file QPSK_Tx_tb_utilization_synth.rpt -pb QPSK_Tx_tb_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
