-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\commhdlQPSKTxRx\CordicKernelMag_block.vhd
-- Created: 2024-01-25 16:33:03
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: CordicKernelMag_block
-- Source Path: commhdlQPSKTxRx/QPSK Rx/Frequency and Time Synchronizer/Phase Ambiguity Estimation and Correction/Phase 
-- Ambiguity Corrector/HDL_CMA_core/CordicKernelMa
-- Hierarchy Level: 5
-- Model version: 7.26
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY CordicKernelMag_block IS
  PORT( xin                               :   IN    std_logic_vector(12 DOWNTO 0);  -- sfix13_En10
        yin                               :   IN    std_logic_vector(12 DOWNTO 0);  -- sfix13_En10
        idx                               :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
        xout                              :   OUT   std_logic_vector(12 DOWNTO 0);  -- sfix13_En10
        yout                              :   OUT   std_logic_vector(12 DOWNTO 0)  -- sfix13_En10
        );
END CordicKernelMag_block;


ARCHITECTURE rtl OF CordicKernelMag_block IS

  -- Signals
  SIGNAL yin_signed                       : signed(12 DOWNTO 0);  -- sfix13_En10
  SIGNAL yLessThanZero                    : std_logic;
  SIGNAL xin_signed                       : signed(12 DOWNTO 0);  -- sfix13_En10
  SIGNAL idx_unsigned                     : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL dynamic_shift_cast               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL yShifted                         : signed(12 DOWNTO 0);  -- sfix13_En10
  SIGNAL xout2                            : signed(12 DOWNTO 0);  -- sfix13_En10
  SIGNAL xout1                            : signed(12 DOWNTO 0);  -- sfix13_En10
  SIGNAL xout_tmp                         : signed(12 DOWNTO 0);  -- sfix13_En10
  SIGNAL dynamic_shift_cast_1             : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL xShifted                         : signed(12 DOWNTO 0);  -- sfix13_En10
  SIGNAL yout2                            : signed(12 DOWNTO 0);  -- sfix13_En10
  SIGNAL yout1                            : signed(12 DOWNTO 0);  -- sfix13_En10
  SIGNAL yout_tmp                         : signed(12 DOWNTO 0);  -- sfix13_En10

BEGIN
  yin_signed <= signed(yin);

  
  yLessThanZero <= '1' WHEN yin_signed < to_signed(16#0000#, 13) ELSE
      '0';

  xin_signed <= signed(xin);

  idx_unsigned <= unsigned(idx);

  dynamic_shift_cast <= resize(idx_unsigned, 8);
  yShifted <= SHIFT_RIGHT(yin_signed, to_integer(dynamic_shift_cast));

  xout2 <= xin_signed + yShifted;

  xout1 <= xin_signed - yShifted;

  
  xout_tmp <= xout2 WHEN yLessThanZero = '0' ELSE
      xout1;

  xout <= std_logic_vector(xout_tmp);

  dynamic_shift_cast_1 <= resize(idx_unsigned, 8);
  xShifted <= SHIFT_RIGHT(xin_signed, to_integer(dynamic_shift_cast_1));

  yout2 <= yin_signed - xShifted;

  yout1 <= yin_signed + xShifted;

  
  yout_tmp <= yout2 WHEN yLessThanZero = '0' ELSE
      yout1;

  yout <= std_logic_vector(yout_tmp);

END rtl;

