-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\commhdlQPSKTxRx\FilterCoef_block1.vhd
-- Created: 2024-01-25 16:33:03
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FilterCoef_block1
-- Source Path: commhdlQPSKTxRx/QPSK Rx/Frequency and Time Synchronizer/Preamble Detector/Correlator/Discrete FIR 
-- Filter/Filter/FilterCoe
-- Hierarchy Level: 6
-- Model version: 7.26
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.QPSK_Rx_pkg.ALL;

ENTITY FilterCoef_block1 IS
  PORT( CoefOutI                          :   OUT   vector_of_std_logic_vector17(0 TO 12)  -- sfix17_En19 [13]
        );
END FilterCoef_block1;


ARCHITECTURE rtl OF FilterCoef_block1 IS

  -- Signals
  SIGNAL CoefData                         : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_1                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_2                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_3                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_4                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_5                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_6                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_7                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_8                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_9                       : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_10                      : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_11                      : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefData_12                      : signed(16 DOWNTO 0);  -- sfix17_En19
  SIGNAL CoefOutI_tmp                     : vector_of_signed17(0 TO 12);  -- sfix17_En19 [13]

BEGIN
  -- CoefReg_1
  CoefData <= to_signed(16#06F66#, 17);

  -- CoefReg_2
  CoefData_1 <= to_signed(-16#06F66#, 17);

  -- CoefReg_3
  CoefData_2 <= to_signed(16#06F66#, 17);

  -- CoefReg_4
  CoefData_3 <= to_signed(-16#06F66#, 17);

  -- CoefReg_5
  CoefData_4 <= to_signed(16#06F66#, 17);

  -- CoefReg_6
  CoefData_5 <= to_signed(16#06F66#, 17);

  -- CoefReg_7
  CoefData_6 <= to_signed(-16#06F66#, 17);

  -- CoefReg_8
  CoefData_7 <= to_signed(-16#06F66#, 17);

  -- CoefReg_9
  CoefData_8 <= to_signed(16#06F66#, 17);

  -- CoefReg_10
  CoefData_9 <= to_signed(16#06F66#, 17);

  -- CoefReg_11
  CoefData_10 <= to_signed(16#06F66#, 17);

  -- CoefReg_12
  CoefData_11 <= to_signed(16#06F66#, 17);

  -- CoefReg_13
  CoefData_12 <= to_signed(16#06F66#, 17);

  CoefOutI_tmp(0) <= CoefData;
  CoefOutI_tmp(1) <= CoefData_1;
  CoefOutI_tmp(2) <= CoefData_2;
  CoefOutI_tmp(3) <= CoefData_3;
  CoefOutI_tmp(4) <= CoefData_4;
  CoefOutI_tmp(5) <= CoefData_5;
  CoefOutI_tmp(6) <= CoefData_6;
  CoefOutI_tmp(7) <= CoefData_7;
  CoefOutI_tmp(8) <= CoefData_8;
  CoefOutI_tmp(9) <= CoefData_9;
  CoefOutI_tmp(10) <= CoefData_10;
  CoefOutI_tmp(11) <= CoefData_11;
  CoefOutI_tmp(12) <= CoefData_12;

  outputgen: FOR k IN 0 TO 12 GENERATE
    CoefOutI(k) <= std_logic_vector(CoefOutI_tmp(k));
  END GENERATE;

END rtl;

