-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\commhdlQPSKTxRx\MATLAB_Function.vhd
-- Created: 2024-01-25 16:33:03
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MATLAB_Function
-- Source Path: commhdlQPSKTxRx/QPSK Rx/Frequency and Time Synchronizer/Packet Controller/MATLAB Function
-- Hierarchy Level: 3
-- Model version: 7.26
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MATLAB_Function IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        valid                             :   IN    std_logic;
        syncPulse                         :   IN    std_logic;
        out_rsvd                          :   OUT   std_logic
        );
END MATLAB_Function;


ARCHITECTURE rtl OF MATLAB_Function IS

  -- Signals
  SIGNAL Reg                              : std_logic;
  SIGNAL Reg_next                         : std_logic;

BEGIN
  MATLAB_Function_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Reg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Reg <= Reg_next;
      END IF;
    END IF;
  END PROCESS MATLAB_Function_1_process;

  MATLAB_Function_1_output : PROCESS (Reg, syncPulse, valid)
  BEGIN
    Reg_next <= Reg;
    IF (Reg AND valid) = '1' THEN 
      Reg_next <= '0';
    END IF;
    IF syncPulse = '1' THEN 
      Reg_next <= '1';
    END IF;
    out_rsvd <= Reg;
  END PROCESS MATLAB_Function_1_output;


END rtl;

