-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\commhdlQPSKTxRx\Phase_Ambiguity_Estimator.vhd
-- Created: 2024-01-25 16:33:03
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Phase_Ambiguity_Estimator
-- Source Path: commhdlQPSKTxRx/QPSK Rx/Frequency and Time Synchronizer/Phase Ambiguity Estimation and Correction/Phase 
-- Ambiguity Estimato
-- Hierarchy Level: 3
-- Model version: 7.26
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.QPSK_Rx_pkg.ALL;

ENTITY Phase_Ambiguity_Estimator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn_re                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        dataIn_im                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        syncPulse                         :   IN    std_logic;
        validIn                           :   IN    std_logic;
        endOut                            :   OUT   std_logic;
        estOut_re                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En29
        estOut_im                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En29
        validOut                          :   OUT   std_logic
        );
END Phase_Ambiguity_Estimator;


ARCHITECTURE rtl OF Phase_Ambiguity_Estimator IS

  -- Component Declarations
  COMPONENT Subsystem
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          L                               :   IN    std_logic;
          H                               :   IN    std_logic;
          Out2                            :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Subsystem1
    PORT( In1                             :   IN    std_logic;
          validIn                         :   IN    std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem
    USE ENTITY work.Subsystem(rtl);

  FOR ALL : Subsystem1
    USE ENTITY work.Subsystem1(rtl);

  -- Constants
  CONSTANT Direct_Lookup_Table_n_D_table_data_re : vector_of_signed16(0 TO 7) := 
    (to_signed(-16#5A82#, 16), to_signed(-16#5A82#, 16), to_signed(16#5A82#, 16), to_signed(16#5A82#, 16),
     to_signed(-16#5A82#, 16), to_signed(-16#5A82#, 16), to_signed(16#5A82#, 16), to_signed(-16#5A82#, 16));  -- sfix16 [8]
  CONSTANT Direct_Lookup_Table_n_D_table_data_im : vector_of_signed16(0 TO 7) := 
    (to_signed(-16#5A82#, 16), to_signed(-16#5A82#, 16), to_signed(16#5A82#, 16), to_signed(16#5A82#, 16),
     to_signed(-16#5A82#, 16), to_signed(-16#5A82#, 16), to_signed(16#5A82#, 16), to_signed(-16#5A82#, 16));  -- sfix16 [8]

  -- Signals
  SIGNAL count_step                       : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL count_from                       : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL count_reset                      : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL HDL_Counter_out1                 : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL count                            : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL need_to_wrap                     : std_logic;
  SIGNAL count_value                      : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Subsystem1_out1                  : std_logic;
  SIGNAL count_1                          : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Subsystem_out1                   : std_logic;
  SIGNAL count_2                          : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Compare_To_Constant_out1         : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL Delay3_out1                      : std_logic;
  SIGNAL Delay7_reg                       : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL Delay7_out1                      : std_logic;
  SIGNAL Delay11_reg                      : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL Delay11_out1                     : std_logic;
  SIGNAL dataIn_re_signed                 : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dataIn_im_signed                 : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay1_out1_re                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay1_out1_im                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay5_reg_re                    : vector_of_signed16(0 TO 1) := (OTHERS => to_signed(16#0000#, 16));  -- sfix16_En14 [2]
  SIGNAL Delay5_reg_im                    : vector_of_signed16(0 TO 1) := (OTHERS => to_signed(16#0000#, 16));  -- sfix16_En14 [2]
  SIGNAL Delay5_out1_re                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay5_out1_im                   : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Delay8_out1                      : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Direct_Lookup_Table_n_D_out1_re  : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Direct_Lookup_Table_n_D_out1_im  : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL conj_cast                        : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL conj_cast_1                      : signed(16 DOWNTO 0);  -- sfix17_En15
  SIGNAL Math_Function_out1_re            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Math_Function_out1_im            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Delay4_reg_re                    : vector_of_signed16(0 TO 1) := (OTHERS => to_signed(16#0000#, 16));  -- sfix16_En15 [2]
  SIGNAL Delay4_reg_im                    : vector_of_signed16(0 TO 1) := (OTHERS => to_signed(16#0000#, 16));  -- sfix16_En15 [2]
  SIGNAL Delay4_out1_re                   : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Delay4_out1_im                   : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Product_mul_temp                 : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL Product_mul_temp_1               : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL Product_mul_temp_2               : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL Product_mul_temp_3               : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL Product_out1_re                  : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL Product_out1_im                  : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL Delay9_reg_re                    : vector_of_signed32(0 TO 1) := (OTHERS => to_signed(0, 32));  -- sfix32_En29 [2]
  SIGNAL Delay9_reg_im                    : vector_of_signed32(0 TO 1) := (OTHERS => to_signed(0, 32));  -- sfix32_En29 [2]
  SIGNAL Delay9_out1_re                   : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL Delay9_out1_im                   : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL Delay2_out1                      : std_logic;
  SIGNAL Delay6_reg                       : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL Delay6_out1                      : std_logic;
  SIGNAL Delay10_reg                      : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL Delay10_out1                     : std_logic;

BEGIN
  u_Subsystem : Subsystem
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              L => syncPulse,
              H => Logical_Operator_out1,
              Out2 => Subsystem_out1
              );

  u_Subsystem1 : Subsystem1
    PORT MAP( In1 => Subsystem_out1,
              validIn => validIn,
              validOut => Subsystem1_out1
              );

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 7
  count_step <= to_unsigned(16#1#, 3);

  count_from <= to_unsigned(16#0#, 3);

  count_reset <= to_unsigned(16#0#, 3);

  count <= HDL_Counter_out1 + count_step;

  
  need_to_wrap <= '1' WHEN HDL_Counter_out1 = to_unsigned(16#7#, 3) ELSE
      '0';

  
  count_value <= count WHEN need_to_wrap = '0' ELSE
      count_from;

  
  count_1 <= HDL_Counter_out1 WHEN Subsystem1_out1 = '0' ELSE
      count_value;

  
  count_2 <= count_1 WHEN Subsystem_out1 = '0' ELSE
      count_reset;

  HDL_Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter_out1 <= to_unsigned(16#0#, 3);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        HDL_Counter_out1 <= count_2;
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;


  
  Compare_To_Constant_out1 <= '1' WHEN HDL_Counter_out1 = to_unsigned(16#7#, 3) ELSE
      '0';

  Logical_Operator_out1 <= Subsystem1_out1 AND Compare_To_Constant_out1;

  Delay3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay3_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay3_out1 <= Logical_Operator_out1;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  Delay7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay7_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay7_reg(0) <= Delay3_out1;
        Delay7_reg(1) <= Delay7_reg(0);
      END IF;
    END IF;
  END PROCESS Delay7_process;

  Delay7_out1 <= Delay7_reg(1);

  Delay11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay11_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay11_reg(0) <= Delay7_out1;
        Delay11_reg(1) <= Delay11_reg(0);
      END IF;
    END IF;
  END PROCESS Delay11_process;

  Delay11_out1 <= Delay11_reg(1);

  dataIn_re_signed <= signed(dataIn_re);

  dataIn_im_signed <= signed(dataIn_im);

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1_re <= to_signed(16#0000#, 16);
      Delay1_out1_im <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_out1_re <= dataIn_re_signed;
        Delay1_out1_im <= dataIn_im_signed;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  Delay5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay5_reg_im(0) <= Delay1_out1_im;
        Delay5_reg_im(1) <= Delay5_reg_im(0);
        Delay5_reg_re(0) <= Delay1_out1_re;
        Delay5_reg_re(1) <= Delay5_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay5_process;

  Delay5_out1_re <= Delay5_reg_re(1);
  Delay5_out1_im <= Delay5_reg_im(1);

  Delay8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay8_out1 <= to_unsigned(16#0#, 3);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay8_out1 <= HDL_Counter_out1;
      END IF;
    END IF;
  END PROCESS Delay8_process;


  Direct_Lookup_Table_n_D_out1_re <= Direct_Lookup_Table_n_D_table_data_re(to_integer(Delay8_out1));
  Direct_Lookup_Table_n_D_out1_im <= Direct_Lookup_Table_n_D_table_data_im(to_integer(Delay8_out1));

  Math_Function_out1_re <= Direct_Lookup_Table_n_D_out1_re;
  conj_cast <= resize(Direct_Lookup_Table_n_D_out1_im, 17);
  conj_cast_1 <=  - (conj_cast);
  
  Math_Function_out1_im <= X"7FFF" WHEN (conj_cast_1(16) = '0') AND (conj_cast_1(15) /= '0') ELSE
      X"8000" WHEN (conj_cast_1(16) = '1') AND (conj_cast_1(15) /= '1') ELSE
      conj_cast_1(15 DOWNTO 0);

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay4_reg_im(0) <= Math_Function_out1_im;
        Delay4_reg_im(1) <= Delay4_reg_im(0);
        Delay4_reg_re(0) <= Math_Function_out1_re;
        Delay4_reg_re(1) <= Delay4_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay4_process;

  Delay4_out1_re <= Delay4_reg_re(1);
  Delay4_out1_im <= Delay4_reg_im(1);

  Product_mul_temp <= Delay5_out1_re * Delay4_out1_re;
  Product_mul_temp_1 <= Delay5_out1_im * Delay4_out1_im;
  Product_out1_re <= Product_mul_temp - Product_mul_temp_1;
  Product_mul_temp_2 <= Delay5_out1_im * Delay4_out1_re;
  Product_mul_temp_3 <= Delay5_out1_re * Delay4_out1_im;
  Product_out1_im <= Product_mul_temp_2 + Product_mul_temp_3;

  Delay9_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay9_reg_im(0) <= Product_out1_im;
        Delay9_reg_im(1) <= Delay9_reg_im(0);
        Delay9_reg_re(0) <= Product_out1_re;
        Delay9_reg_re(1) <= Delay9_reg_re(0);
      END IF;
    END IF;
  END PROCESS Delay9_process;

  Delay9_out1_re <= Delay9_reg_re(1);
  Delay9_out1_im <= Delay9_reg_im(1);

  estOut_re <= std_logic_vector(Delay9_out1_re);

  estOut_im <= std_logic_vector(Delay9_out1_im);

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay2_out1 <= Subsystem1_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  Delay6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay6_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay6_reg(0) <= Delay2_out1;
        Delay6_reg(1) <= Delay6_reg(0);
      END IF;
    END IF;
  END PROCESS Delay6_process;

  Delay6_out1 <= Delay6_reg(1);

  Delay10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay10_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay10_reg(0) <= Delay6_out1;
        Delay10_reg(1) <= Delay10_reg(0);
      END IF;
    END IF;
  END PROCESS Delay10_process;

  Delay10_out1 <= Delay10_reg(1);

  endOut <= Delay11_out1;

  validOut <= Delay10_out1;

END rtl;

